# check_docker.yml
---

# Check if 'postgres_data_dir' variable is defined in inventory file
# This task will only run if 'pg_hostname' variable is undefined or an empty string
- name: postgres_data_dir should be defined
  assert:
    that:
      - postgres_data_dir is defined and postgres_data_dir != ''
    msg: "Set the value of 'postgres_data_dir' in the inventory file."
  when: pg_hostname is not defined or pg_hostname == ''
