# main.yml
---

# Check if 'admin_password' variable is defined in inventory file
- name: admin_password should be defined
  assert:
    that:
      - admin_password is defined and admin_password != ''
    msg: "Set the value of 'admin_password' in the inventory file."

# Launch 'check_docker.yml' file when 'openshift_host' variable is undefined or an empty string
- include_tasks: check_docker.yml
  when: openshift_host is not defined or openshift_host == ''
