---

- name: Install Apache
  apt:
          name: apache2
          state: latest

- name: Start Apache service
  service:
          name: apache2
          state: started        

- name: Install ufw
  apt:
          name: ufw
          state: present      

- name: Enable ufw
  ufw:
          state: enabled

- name: Open port 80
  ufw:
          rule: allow
          port: "80"

- name: Open port 443
  ufw:
          rule: allow
          port: "443"

- name: Open port 22
  ufw:
          rule: allow
          port: "22"
  notify:
          - "restart firewall"
          - "restart apache"
