---

- name: Import proxy configuration
  template:
          src: files/proxy.conf
          dest: /etc/apache2/sites-available/proxy.conf
          owner: root
          group: root
          mode: '0644'

- name: Enable apache modules
  apache2_module:
          name: "{{ item }}"
          state: present
  with_items:
          - proxy
          - proxy_http
          - proxy_balancer
          - lbmethod_byrequests

- name: Restart Apache
  service:
          name: apache2
          state: restarted

- name: Enable proxy configuration
  command: a2ensite proxy.conf
  args:
          chdir: /etc/apache2/sites-available/
          creates: /etc/apache2/sites-enabled/proxy.conf
  register: proxy_result

- name: Restart Apache service
  service:
          name: apache2
          state: restarted
  when: proxy_result is success
