---

- name: Install httpd
  yum:
          name: httpd
          state: latest
  retries: 3
  delay: 10
  register: httpd_result

- name: Start httpd service
  service:
          name: httpd
          state: started
          enabled: yes
  when: httpd_result is success

#### OPEN HTTP PORT WITH FIREWALLD #################################
#### IF FIREWALLD ISN'T AVAILABLE (FOR EXAMPLE IN UBI 8) ###########
#### IPTABLES IS INSTALLED AND THE PORT IS OPENED WITH THIS ########

- name: Open port for httpd service
  firewalld:
          service: http
          permanent: true
          state: enabled
  register: firewalld_result

- name: Restart firewall
  service:
          name: firewalld
          state: reloaded
  when: firewalld_result is success

- name: Install iptables if firewalld isn't available
  yum:
          name: iptables
          state: present
  when: firewalld_result is failed

- name: Open port for httpd with iptables
  iptables:
          chain: INPUT
          protocol: tcp
          destination_port: 80
          jump: ACCEPT
  when: firewalld_result is failed

##########################################################################

- name: Disable SELINUX
  template:
          src: files/config
          dest: /etc/selinux/config
          owner: root
          group: root
          mode: '0644'
  register: selinux_result

- name: Start httpd service
  service:
          name: httpd
          state: started
          enabled: yes
  when: selinux_result is success

- name: Reboot server
  reboot:
          reboot_timeout: 30
          post_reboot_delay: 30
  when: selinux_result is success
