---

- name: Restart firewall
  ufw:
          state: reloaded
  listen: "restart firewall"

- name: Restart Apache service
  become: yes
  service:
          name: apache2
          state: restarted
  listen: "restart apache"
