---
- name: Install MariaDB
  hosts: DBservers
  become: true

  roles:
          - role: mariadb_redhat
            when: ansible_distribution == 'CentOS'

          - role: mariadb_debian
            when: ansible_distribution == 'Debian'
