---
- name: Install Prestashop
  hosts: Prestashop
  become: true

  roles:
          - role: prestashop_redhat
            when: ansible_distribution == 'CentOS'

          - role: prestashop_debian
            when: ansible_distribution == 'Debian'
