---
- name: Install Prestashop
  hosts: Wordpress
  become: true

  roles:
          - role: prestashop_centos
            when: ansible_distribution == 'CentOS'

          - role: prestashop_debian
            when: ansible_distribution == 'Debian'
