---

- name: Import proxy config
  template:
          src: files/proxy.conf
          dest: /etc/httpd/conf.d/proxy.conf
          owner: root
          group: root
          mode: '0644'
  register: template_result

- name: Restart httpd service
  service:
          name: httpd
          state: restarted
  when: template_result is success
