---
# main.yml

- name: Install dependencies
  apt:
    name:
      - curl
      - gpg
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker-CE
  apt:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install Docker with pip
  pip:
    name: docker==6.1.3
    extra_args: --break-system-packages

- name: Install pyyaml with pip
  pip:
    name: pyyaml==5.3.1
    extra_args: --break-system-packages

- name: Install Docker Compose with pip
  pip:
    name: docker-compose
    extra_args: --break-system-packages
