---
- name: Reverse proxy configuration
  hosts: ReverseProxy
  become: true

  roles:
    - role: proxy_redhat
      when: ansible_distribution == 'CentOS'

    - role: proxy_debian
      when: ansible_distribution == 'Debian'
