---
- name: Apache installation
  hosts: Apache
  become: true

  roles:
    - role: apache_redhat
      when: ansible_distribution == 'CentOS'

    - role: apache_debian
      when: ansible_distribution == 'Debian'
