---

- name: Create {{ postgres_data_dir }} directory
  file:
    path: "{{ postgres_data_dir }}"
    state: directory

- name: Get full path of postgres data dir
  shell: "echo {{ postgres_data_dir }}"
  register: fq_postgres_data_dir

- name: Register temporary docker container
  set_fact:
    container_command: "docker run --rm -v '{{ fq_postgres_data_dir.stdout }}:/var/lib/postgresql' centos:8 bash -c "

- name: Check for existing Postgres data (run from inside the container for access to file)
  shell:
    cmd: |
      {{ container_command }} "[[ -f /var/lib/postgresql/10/data/PG_VERSION ]] && echo 'exists'"
  register: pg_version_file
  ignore_errors: true
