# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "tfg-control-node" do |master|
    master.vm.box = "debian/bookworm64"
    master.vm.hostname = "tfg-control-node"
    master.vm.network :private_network, ip: "192.168.100.10"
    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "tfg-control-node"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end
    #master.vm.provision "shell", path: "./master.sh"
  end
end
