---

- name: Install php and extensions
  apt:
    name:
      - php
      - php-curl
      - php-intl
      - php-zip
      - php-mysql
      - php-gd
      - php-mbstring
      - php-xml
      - unzip
    state: present
  retries: 3
  delay: 10
  register: php_result

- name: Restart Apache service
  service:
    name: apache2
    state: restarted
  when: php_result is success
  
- name: Download Prestashop
  get_url:
          url: https://download.prestashop.com/download/releases/prestashop_1.7.7.3.zip
          dest: /tmp/prestashop_1.7.7.3.zip
  retries: 3
  delay: 10

- name: Extract Prestashop files
  command: unzip prestashop_1.7.7.3.zip -d prestashop
  args:
    chdir: /tmp

- name: Move PrestaShop to the web directory
  command: mv /tmp/prestashop /var/www/html/prestashop
  args:
    creates: /var/www/html/prestashop

- name: Change owner of PrestaShop directory
  file:
    path: /var/www/html/prestashop
    owner: www-data
    group: www-data
    recurse: yes

- name: Change permissions of PrestaShop directory
  file:
    path: /var/www/html/prestashop
    mode: 0755
    recurse: yes

- name: Enable mod_rewrite module
  command: a2enmod rewrite
  register: enable_rewrite

- name: Restart Apache service
  service:
    name: apache2
    state: restarted
  when: enable_rewrite is success

